"$schema" = 'https://starship.rs/config-schema.json'

format = "$python$directory$git_branch$git_status$character"

[git_branch]
format = '[\($branch\)]($style) '

[python]
format = '(\($virtualenv\) )($style)'

# Preset from starship for no nerd font
[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[erlang]
symbol = "ⓔ "

[nodejs]
symbol = "[⬢](bold green) "

[pulumi]
symbol = "🧊 "

[typst]
symbol = "t "
